### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [illlllya/codecademy_api_course#4]
Overall I'm impressed with the cleanliness of your code and its organization.

I know this is the first project so it might've not been as intense as the projects to come but I'm confident in your ability from what I see!

Also great job adding in comments as it aids those reading your code. Please do continue this in the future for projects and when on the job!

Not sure if it was just a personal choice or an external one but I noticed you didn't tackle the bonus assignment (YAML Saving and Loading)?

Great job, will look forward to seeing your next submission!

**Comment by illlllya** [comment]
Totally forgot about the bonus assignment haha. This one took me a pretty long time so I think I was just mentally wiped, but I'll give it a try this weekend.
